Setting up RSpec Testing
gealsanchez/school-library pull request #7
Opened 2023-04-26 21:27 UTC by chelobotix

In this PR we fulfilled the following tasks:
- [x] Add unit tests for all the methods in all the classes:

- Book
- Person
- Student
- Teacher
- Classroom
- Rental
- Decorator Classes

2023-04-26 21:44 UTC, VICTOR-CHUKWU requested changes
Hi @gealsanchez  👋  

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost](https://media.giphy.com/media/R2m2NzVxQ3pbG/giphy.gif)

## Highlights
- Good PR
- Good commit
- All linters passed


## Required Changes ♻️

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-26 21:44 UTC, VICTOR-CHUKWU commented on spec/person_spec.rb
> +end
- [ ] good job, but some tests are missing, you are missing tests to check if `The constructor method sets default value for the optional name parameter if it is not provided` and also tests for the method `correct_name`

2023-04-26 21:44 UTC, VICTOR-CHUKWU commented on spec/student_spec.rb
> +  end
- [ ] Good job, but some tests are missing, you are missing tests to check if `The constructor method sets the default value for the optional name parameter if it is not provided `

2023-04-26 21:44 UTC, VICTOR-CHUKWU commented on spec/teacher_spec.rb
> +end
- [ ] Good job, but some tests are missing, you are missing tests to check if `The constructor method sets the default value for the optional name parameter if it is not provided and also tests for the method `can_use_services?`

2023-04-27 04:21 UTC, amejid approved these changes
Hi @gealsanchez & @chelobotix, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media1.giphy.com/media/RltjLEzzB87ErJdxHz/giphy.gif"/>

## Highlights
- Linter checks passing :heavy_check_mark: 
- Correct use of Gitflow :heavy_check_mark: 
- Methods covered in tests :heavy_check_mark: 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-27 13:33 UTC, merged